# Generated by Django 3.1.5 on 2021-01-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Port Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=20)),
                ("model_link", models.URLField(max_length=255)),
                ("gpio", models.BooleanField(default=True)),
                ("ports", models.ManyToManyField(to="io_ssh.PortType")),
            ],
            options={
                "verbose_name_plural": "Device Types",
                "ordering": ["model"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="io_ssh.devicetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Devices",
                "ordering": ["name"],
            },
        ),
    ]
