# Generated by Django 3.1.6 on 2021-02-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("io_ssh", "0002_auto_20210207_2027"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicetype",
            name="ports",
        ),
    ]
