# Generated by Django 3.1.7 on 2021-02-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("io_ssh", "0003_remove_devicetype_ports"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortType",
        ),
        migrations.AlterField(
            model_name="device",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="io_ssh.devicetype",
                verbose_name="model",
            ),
        ),
    ]
